/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MovimentoDAO;
import dao.TipoMovimentoDAO;
import dominio.Movimento;
import dominio.TipoMovimento;
import dominio.Usuario;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bruno
 */
public class TelaInicial extends javax.swing.JFrame {

    public static Usuario tipoUser;
    public static TelaCadEstoque telaCadEstoque = new TelaCadEstoque();;
    TelaVendas telaVendas = null;

    /**
     * Creates new form TelaInicial
     *
     */
    public TelaInicial(Usuario usuario) {
        setExtendedState(MAXIMIZED_BOTH);
        tipoUser = usuario;
        String tipo = tipoUser.getTipo();
        String nome = tipoUser.getLogin();

        initComponents();
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        
        lbTipoUsuario.setText(tipoUser.getTipo().toString());
        
        TelaVendas telaVendas = null;
        
        if("User".equals(tipoUser.getTipo())){
            btnUsuarios.setEnabled(false);
            btnRelatorio.setEnabled(false);
        }

        TelaCadUsuario telaCadUsuario = new TelaCadUsuario();
        TelaCadProduto telaCadProduto = new TelaCadProduto();
        TelaCadCli telaCadCli = new TelaCadCli();
        TelaCadFornecedor telaCadFornecedor = new TelaCadFornecedor();
        TelaCadGenero telaCadGenero = new TelaCadGenero();
        
        TelaRelatorio telaRelatorio = new TelaRelatorio();
        TelaBackup telaBackup = new TelaBackup();
        TelaCalendario telaCalendario = new TelaCalendario();

        //adiciona telas ao Painel
        jpPrincipal.setVisible(false);
        jpPrincipal.add(telaCadUsuario, "telaCadUsuario");
        jpPrincipal.add(telaCadProduto, "telaCadProduto");
        jpPrincipal.add(telaCadFornecedor, "telaCadFornecedor");
        jpPrincipal.add(telaCadGenero, "telaCadGenero");
        jpPrincipal.add(telaCadCli, "telaCadCli");
        jpPrincipal.add(telaCadEstoque, "telaCadEstoque");
        jpPrincipal.add(telaRelatorio, "telaRelatorio");
        jpPrincipal.add(telaCalendario, "telaCalendario");
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GavetaOpc = new javax.swing.JPanel();
        jbSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbTipoUsuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        painelOpcoes = new javax.swing.JPanel();
        lblOpc = new javax.swing.JLabel();
        painelCadastros = new javax.swing.JPanel();
        lblCad = new javax.swing.JLabel();
        painelMovimentacoes = new javax.swing.JPanel();
        lblMov = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        painelOpc = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        painelMov = new javax.swing.JPanel();
        btnRelatorio = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        painelCad = new javax.swing.JPanel();
        btnFornecedores = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnGeneros = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jpPrincipal = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GavetaOpc.setBackground(new java.awt.Color(51, 51, 51));
        GavetaOpc.setForeground(new java.awt.Color(51, 51, 51));

        jbSair.setBackground(java.awt.Color.lightGray);
        jbSair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbSair.setText("Sair");
        jbSair.setBorderPainted(false);
        jbSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSair.setFocusPainted(false);
        jbSair.setFocusable(false);
        jbSair.setRequestFocusEnabled(false);
        jbSair.setRolloverEnabled(false);
        jbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbSairMouseExited(evt);
            }
        });
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jPanel3.setBackground(java.awt.Color.lightGray);

        lbTipoUsuario.setBackground(java.awt.Color.lightGray);
        lbTipoUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbTipoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lbTipoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel8.setBackground(java.awt.Color.lightGray);
        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Usuário");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        painelOpcoes.setBackground(java.awt.Color.lightGray);

        lblOpc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblOpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOpc.setText("Opções");
        lblOpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpc.setFocusable(false);
        lblOpc.setRequestFocusEnabled(false);
        lblOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpcMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelOpcoesLayout = new javax.swing.GroupLayout(painelOpcoes);
        painelOpcoes.setLayout(painelOpcoesLayout);
        painelOpcoesLayout.setHorizontalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOpc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelOpcoesLayout.setVerticalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOpc, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        painelCadastros.setBackground(java.awt.Color.lightGray);

        lblCad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCad.setText("Cadastros");
        lblCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCad.setFocusable(false);
        lblCad.setRequestFocusEnabled(false);
        lblCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelCadastrosLayout = new javax.swing.GroupLayout(painelCadastros);
        painelCadastros.setLayout(painelCadastrosLayout);
        painelCadastrosLayout.setHorizontalGroup(
            painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelCadastrosLayout.setVerticalGroup(
            painelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCad, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        painelMovimentacoes.setBackground(java.awt.Color.lightGray);

        lblMov.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMov.setText("Movimentos");
        lblMov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMov.setFocusable(false);
        lblMov.setRequestFocusEnabled(false);
        lblMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMovMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelMovimentacoesLayout = new javax.swing.GroupLayout(painelMovimentacoes);
        painelMovimentacoes.setLayout(painelMovimentacoesLayout);
        painelMovimentacoesLayout.setHorizontalGroup(
            painelMovimentacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelMovimentacoesLayout.setVerticalGroup(
            painelMovimentacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMov, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setLabel("Home");
        jButton1.setMaximumSize(new java.awt.Dimension(92, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(92, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(92, 30));
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVendas.setBackground(java.awt.Color.lightGray);
        btnVendas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVendas.setText("Vendas");
        btnVendas.setBorderPainted(false);
        btnVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendas.setFocusPainted(false);
        btnVendas.setFocusable(false);
        btnVendas.setRequestFocusEnabled(false);
        btnVendas.setRolloverEnabled(false);
        btnVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendasMouseExited(evt);
            }
        });
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GavetaOpcLayout = new javax.swing.GroupLayout(GavetaOpc);
        GavetaOpc.setLayout(GavetaOpcLayout);
        GavetaOpcLayout.setHorizontalGroup(
            GavetaOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GavetaOpcLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(GavetaOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelOpcoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelMovimentacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelCadastros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(193, 193, 193))
        );
        GavetaOpcLayout.setVerticalGroup(
            GavetaOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GavetaOpcLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelMovimentacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(GavetaOpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 770));

        painelOpc.setBackground(new java.awt.Color(51, 51, 51));
        painelOpc.setForeground(new java.awt.Color(51, 51, 51));
        painelOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelOpcMouseExited(evt);
            }
        });
        painelOpc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(java.awt.Color.lightGray);
        jButton11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton11.setText("Backup");
        jButton11.setBorderPainted(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverEnabled(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        painelOpc.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 44));

        jButton13.setBackground(java.awt.Color.lightGray);
        jButton13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton13.setText("Calculadora");
        jButton13.setBorderPainted(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        jButton13.setFocusable(false);
        jButton13.setRequestFocusEnabled(false);
        jButton13.setRolloverEnabled(false);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton13MouseExited(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        painelOpc.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 240, 40));

        jButton10.setBackground(java.awt.Color.lightGray);
        jButton10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton10.setText("Calendário");
        jButton10.setBorderPainted(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverEnabled(false);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        painelOpc.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 40));

        jPanel1.add(painelOpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 298, 260, 160));

        painelMov.setBackground(new java.awt.Color(51, 51, 51));
        painelMov.setForeground(new java.awt.Color(51, 51, 51));
        painelMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelMovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelMovMouseExited(evt);
            }
        });

        btnRelatorio.setBackground(java.awt.Color.lightGray);
        btnRelatorio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRelatorio.setText("Relatórios");
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setFocusable(false);
        btnRelatorio.setRequestFocusEnabled(false);
        btnRelatorio.setRolloverEnabled(false);
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseExited(evt);
            }
        });
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnEstoque.setBackground(java.awt.Color.lightGray);
        btnEstoque.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEstoque.setText("Entradas");
        btnEstoque.setBorderPainted(false);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.setFocusPainted(false);
        btnEstoque.setFocusable(false);
        btnEstoque.setRequestFocusEnabled(false);
        btnEstoque.setRolloverEnabled(false);
        btnEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseExited(evt);
            }
        });
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelMovLayout = new javax.swing.GroupLayout(painelMov);
        painelMov.setLayout(painelMovLayout);
        painelMovLayout.setHorizontalGroup(
            painelMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(btnEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelMovLayout.setVerticalGroup(
            painelMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(painelMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 238, 260, 120));

        painelCad.setBackground(new java.awt.Color(51, 51, 51));
        painelCad.setForeground(new java.awt.Color(51, 51, 51));
        painelCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelCadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelCadMouseExited(evt);
            }
        });
        painelCad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFornecedores.setBackground(java.awt.Color.lightGray);
        btnFornecedores.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnFornecedores.setText("Fornecedores");
        btnFornecedores.setBorderPainted(false);
        btnFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFornecedores.setFocusPainted(false);
        btnFornecedores.setFocusable(false);
        btnFornecedores.setRequestFocusEnabled(false);
        btnFornecedores.setRolloverEnabled(false);
        btnFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFornecedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFornecedoresMouseExited(evt);
            }
        });
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });
        painelCad.add(btnFornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 40));

        btnProdutos.setBackground(java.awt.Color.lightGray);
        btnProdutos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnProdutos.setText("Produtos");
        btnProdutos.setBorderPainted(false);
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.setFocusPainted(false);
        btnProdutos.setFocusable(false);
        btnProdutos.setRequestFocusEnabled(false);
        btnProdutos.setRolloverEnabled(false);
        btnProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutosMouseExited(evt);
            }
        });
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        painelCad.add(btnProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, 40));

        btnClientes.setBackground(java.awt.Color.lightGray);
        btnClientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorderPainted(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setFocusPainted(false);
        btnClientes.setFocusable(false);
        btnClientes.setRequestFocusEnabled(false);
        btnClientes.setRolloverEnabled(false);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        painelCad.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 240, 40));

        btnGeneros.setBackground(java.awt.Color.lightGray);
        btnGeneros.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGeneros.setText("Gêneros");
        btnGeneros.setBorderPainted(false);
        btnGeneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGeneros.setFocusPainted(false);
        btnGeneros.setFocusable(false);
        btnGeneros.setRequestFocusEnabled(false);
        btnGeneros.setRolloverEnabled(false);
        btnGeneros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerosMouseExited(evt);
            }
        });
        btnGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerosActionPerformed(evt);
            }
        });
        painelCad.add(btnGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 40));

        btnUsuarios.setBackground(java.awt.Color.lightGray);
        btnUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUsuarios.setText("Usuários");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.setFocusable(false);
        btnUsuarios.setRequestFocusEnabled(false);
        btnUsuarios.setRolloverEnabled(false);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        painelCad.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, 40));

        jPanel1.add(painelCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 178, 260, 260));

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpPrincipal.setFocusCycleRoot(true);
        jpPrincipal.setOpaque(false);
        jpPrincipal.setPreferredSize(new java.awt.Dimension(1190, 640));
        jpPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpPrincipalMouseExited(evt);
            }
        });
        jpPrincipal.setLayout(new java.awt.CardLayout());
        jPanel1.add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 1190, 630));

        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 790));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/s-new-01_0.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 290, 400));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        btnSair.setBackground(new java.awt.Color(0, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("X");
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusPainted(false);
        btnSair.setFocusable(false);
        btnSair.setRolloverEnabled(false);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setText("-");
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.setFocusable(false);
        btnMinimizar.setRolloverEnabled(false);
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoBarra.png"))); // NOI18N
        jLabel3.setText("isContque");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1103, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo-azul-abstrato-hd (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        //Cria o cardLayout a partir do layout do JpPrinical
        CardLayout cl = (CardLayout) jpPrincipal.getLayout();
        //mostra o cardSelecionado
        cl.show(jpPrincipal, "telaCadEstoque");
        jpPrincipal.setVisible(true);

        btnEstoque.setBackground(Color.darkGray);
        btnEstoque.setForeground(Color.WHITE);

        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        CardLayout cl = (CardLayout) (jpPrincipal.getLayout());
        cl.show(jpPrincipal, "telaCadUsuario");
        jpPrincipal.setVisible(true);

        btnUsuarios.setBackground(Color.darkGray);
        btnUsuarios.setForeground(Color.WHITE);

        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);


    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?", "confirmação", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            TipoMovimentoDAO tipoMovimentoDAO = new TipoMovimentoDAO();
            TipoMovimento tipoMov = tipoMovimentoDAO.buscar(5);

            Movimento movimento = new Movimento();
            movimento.setDataExecucao(new Date());
            movimento.setTipoMovimento(tipoMov);
            movimento.setUsuario(tipoUser);

            MovimentoDAO movimentoDAO = new MovimentoDAO();
            movimentoDAO.inserir(movimento);
            System.exit(0);
        }
    }//GEN-LAST:event_jbSairActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed

        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        
        if (telaVendas == null) {       
           telaVendas = new TelaVendas(tipoUser);
           telaVendas.setVisible(true);      
        } else {
            if(!telaVendas.isVisible()){
                telaVendas.setVisible(true);
            }else{
                telaVendas.setExtendedState(JFrame.NORMAL);
                telaVendas.toFront();
            }
            
            
        }

        btnVendas.setBackground(Color.darkGray);
        btnVendas.setForeground(Color.WHITE);

        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        CardLayout cl = (CardLayout) (jpPrincipal.getLayout());
        cl.show(jpPrincipal, "telaCadCli");
        jpPrincipal.setVisible(true);

        btnClientes.setBackground(Color.darkGray);
        btnClientes.setForeground(Color.WHITE);

        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        CardLayout cl = (CardLayout) jpPrincipal.getLayout();
        cl.show(jpPrincipal, "telaCadFornecedor");
        jpPrincipal.setVisible(true);

        btnFornecedores.setBackground(Color.darkGray);
        btnFornecedores.setForeground(Color.WHITE);

        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        CardLayout cl = (CardLayout) (jpPrincipal.getLayout());
        cl.show(jpPrincipal, "telaCadProduto");
        jpPrincipal.setVisible(true);

        btnProdutos.setBackground(Color.darkGray);
        btnProdutos.setForeground(Color.WHITE);

        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);
        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked

    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(true);
        btnUsuarios.setBackground(Color.darkGray);
        btnUsuarios.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(true);
        btnClientes.setBackground(Color.darkGray);
        btnClientes.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnFornecedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFornecedoresMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(true);
        btnFornecedores.setBackground(Color.darkGray);
        btnFornecedores.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFornecedoresMouseEntered

    private void btnProdutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(true);
        btnProdutos.setBackground(Color.darkGray);
        btnProdutos.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnProdutosMouseEntered

    private void btnEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(true);
        painelCad.setVisible(false);
        btnEstoque.setBackground(Color.darkGray);
        btnEstoque.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnEstoqueMouseEntered

    private void btnVendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendasMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnVendas.setBackground(Color.darkGray);
        btnVendas.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVendasMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnVendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendasMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnVendasMouseExited

    private void btnEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnEstoqueMouseExited

    private void btnProdutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnProdutosMouseExited

    private void btnFornecedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFornecedoresMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnFornecedoresMouseExited

    private void jbSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSairMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        jbSair.setBackground(Color.red);
        jbSair.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbSairMouseEntered

    private void jbSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSairMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        jbSair.setBackground(Color.lightGray);
        jbSair.setForeground(Color.BLACK);
    }//GEN-LAST:event_jbSairMouseExited

    private void btnGenerosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerosMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(true);
        btnGeneros.setBackground(Color.darkGray);
        btnGeneros.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGenerosMouseEntered

    private void btnGenerosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerosMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnGenerosMouseExited

    private void btnGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerosActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        CardLayout cl = (CardLayout) jpPrincipal.getLayout();
        cl.show(jpPrincipal, "telaCadGenero");
        jpPrincipal.setVisible(true);

        btnGeneros.setBackground(Color.darkGray);
        btnGeneros.setForeground(Color.WHITE);

        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnGenerosActionPerformed

    private void btnRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(true);
        painelCad.setVisible(false);
        btnRelatorio.setBackground(Color.darkGray);
        btnRelatorio.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRelatorioMouseEntered

    private void btnRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        btnRelatorio.setBackground(Color.lightGray);
        btnRelatorio.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnRelatorioMouseExited

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        CardLayout cl = (CardLayout) (jpPrincipal.getLayout());
        cl.show(jpPrincipal, "telaRelatorio");
        jpPrincipal.setVisible(true);

        btnRelatorio.setBackground(Color.darkGray);
        btnRelatorio.setForeground(Color.WHITE);

        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        jButton1.setBackground(Color.darkGray);
        jButton1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        jButton1.setBackground(Color.lightGray);
        jButton1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jpPrincipal.setVisible(false);

        jButton1.setBackground(Color.darkGray);
        jButton1.setForeground(Color.WHITE);

        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);
        btnRelatorio.setBackground(Color.lightGray);
        btnRelatorio.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?", "confirmação", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            TipoMovimentoDAO tipoMovimentoDAO = new TipoMovimentoDAO();
            TipoMovimento tipoMov = tipoMovimentoDAO.buscar(5);

            Movimento movimento = new Movimento();
            movimento.setDataExecucao(new Date());
            movimento.setTipoMovimento(tipoMov);
            movimento.setUsuario(tipoUser);

            MovimentoDAO movimentoDAO = new MovimentoDAO();
            movimentoDAO.inserir(movimento);
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setBackground(Color.red);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setBackground(Color.orange);
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        btnSair.setBackground(Color.black);
    }//GEN-LAST:event_btnSairMouseExited

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setBackground(Color.black);
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        jpPrincipal.setVisible(false);

        TelaBackup telabackup = new TelaBackup();
        telabackup.setVisible(true);

        jButton11.setBackground(Color.darkGray);
        jButton11.setForeground(Color.WHITE);

        btnClientes.setBackground(Color.lightGray);
        btnClientes.setForeground(Color.BLACK);
        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void painelOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelOpcMouseExited
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
    }//GEN-LAST:event_painelOpcMouseExited

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        painelOpc.setVisible(true);
        jButton10.setBackground(Color.darkGray);
        jButton10.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseEntered
        painelOpc.setVisible(true);
        jButton13.setBackground(Color.darkGray);
        jButton13.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton13MouseEntered

    private void painelOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelOpcMouseEntered
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        painelOpc.setVisible(true);
    }//GEN-LAST:event_painelOpcMouseEntered

    private void jButton13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseExited
        jButton13.setBackground(Color.lightGray);
        jButton13.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton13MouseExited

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        jButton10.setBackground(Color.lightGray);
        jButton10.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton10MouseExited

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        painelOpc.setVisible(true);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        jButton11.setBackground(Color.darkGray);
        jButton11.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(true);
        painelCad.setVisible(false);
        jButton11.setBackground(Color.lightGray);
        jButton11.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton11MouseExited

    private void lblOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpcMouseExited
        if (painelOpc.isVisible()) {
            painelOpc.setVisible(true);
        } else {
            painelOpc.setVisible(false);
        }
        painelOpcoes.setBackground(Color.lightGray);
        lblOpc.setForeground(Color.black);
    }//GEN-LAST:event_lblOpcMouseExited

    private void lblOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpcMouseEntered
        if (painelCad.isVisible() || painelMov.isVisible()) {
            painelMov.setVisible(false);
            painelCad.setVisible(false);
            painelOpc.setVisible(true);
        } else {
            painelOpc.setVisible(true);
            painelOpcoes.setBackground(Color.darkGray);
            lblOpc.setForeground(Color.white);
        }
    }//GEN-LAST:event_lblOpcMouseEntered

    private void lblCadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadMouseEntered
        if (painelMov.isVisible() || painelOpc.isVisible()) {
            painelMov.setVisible(false);
            painelOpc.setVisible(false);
            painelCad.setVisible(true);
        } else {
            painelCad.setVisible(true);
            painelCadastros.setBackground(Color.darkGray);
            lblCad.setForeground(Color.white);
        }
    }//GEN-LAST:event_lblCadMouseEntered

    private void lblCadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadMouseExited
        if (painelCad.isVisible()) {
            painelCad.setVisible(true);
        } else {
            painelCad.setVisible(false);
        }
        painelCadastros.setBackground(Color.lightGray);
        lblCad.setForeground(Color.black);
    }//GEN-LAST:event_lblCadMouseExited

    private void lblMovMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovMouseEntered
        if (painelCad.isVisible() || painelOpc.isVisible()) {
            painelCad.setVisible(false);
            painelOpc.setVisible(false);
            painelMov.setVisible(true);
        } else {
            painelMov.setVisible(true);
            painelMovimentacoes.setBackground(Color.darkGray);
            lblMov.setForeground(Color.white);
        }
    }//GEN-LAST:event_lblMovMouseEntered

    private void lblMovMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovMouseExited
        if (painelMov.isVisible()) {
            painelMov.setVisible(true);
        } else {
            painelMov.setVisible(false);
        }
        painelMovimentacoes.setBackground(Color.lightGray);
        lblMov.setForeground(Color.black);
    }//GEN-LAST:event_lblMovMouseExited

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        CardLayout cl = (CardLayout) (jpPrincipal.getLayout());
        cl.show(jpPrincipal, "telaCalendario");
        jpPrincipal.setVisible(true);

        btnClientes.setBackground(Color.darkGray);
        btnClientes.setForeground(Color.WHITE);

        btnUsuarios.setBackground(Color.lightGray);
        btnUsuarios.setForeground(Color.BLACK);
        btnFornecedores.setBackground(Color.lightGray);
        btnFornecedores.setForeground(Color.BLACK);
        btnProdutos.setBackground(Color.lightGray);
        btnProdutos.setForeground(Color.BLACK);
        btnEstoque.setBackground(Color.lightGray);
        btnEstoque.setForeground(Color.BLACK);
        btnVendas.setBackground(Color.lightGray);
        btnVendas.setForeground(Color.BLACK);
        btnGeneros.setBackground(Color.lightGray);
        btnGeneros.setForeground(Color.BLACK);


    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
        painelMov.setVisible(false);

        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException exc) {
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void painelCadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCadMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(true);
    }//GEN-LAST:event_painelCadMouseEntered

    private void painelCadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCadMouseExited
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
    }//GEN-LAST:event_painelCadMouseExited

    private void painelMovMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMovMouseExited
        painelMov.setVisible(false);
        painelCad.setVisible(false);
        painelOpc.setVisible(false);
    }//GEN-LAST:event_painelMovMouseExited

    private void painelMovMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMovMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(true);
        painelCad.setVisible(false);
    }//GEN-LAST:event_painelMovMouseEntered

    private void jpPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
    }//GEN-LAST:event_jpPrincipalMouseEntered

    private void jpPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPrincipalMouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
    }//GEN-LAST:event_jpPrincipalMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        painelOpc.setVisible(false);
        painelMov.setVisible(false);
        painelCad.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("basic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaInicial(tipoUser).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GavetaOpc;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnGeneros;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbSair;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JLabel lbTipoUsuario;
    private javax.swing.JLabel lblCad;
    private javax.swing.JLabel lblMov;
    private javax.swing.JLabel lblOpc;
    private javax.swing.JPanel painelCad;
    private javax.swing.JPanel painelCadastros;
    private javax.swing.JPanel painelMov;
    private javax.swing.JPanel painelMovimentacoes;
    private javax.swing.JPanel painelOpc;
    private javax.swing.JPanel painelOpcoes;
    // End of variables declaration//GEN-END:variables
}
