/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.PrimeiroInsert;
import dao.MovimentoDAO;
import dao.TipoMovimentoDAO;
import dao.UsuarioDAO;
import dominio.Movimento;
import dominio.TipoMovimento;
import dominio.Usuario;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.TouchPoint;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import static view.TelaInicial.tipoUser;

/**
 *
 * @author Bruno
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadUsuario
     */
    public TelaLogin() {
        initComponents();
        lblCarregando.setVisible(false);
        jProgressBar1.setVisible(false);
        setPreferredSize(null);
        
        getRootPane().setDefaultButton(btnEntrar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txLoginErro = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblCarregando = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblSair = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txLoginErro.setBackground(new java.awt.Color(255, 255, 255));
        txLoginErro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txLoginErro.setForeground(new java.awt.Color(255, 255, 255));
        txLoginErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txLoginErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 190, 20));

        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 170, 20));

        lblCarregando.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCarregando.setForeground(new java.awt.Color(255, 255, 255));
        lblCarregando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarregando.setText("Usuário");
        lblCarregando.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(lblCarregando, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 280, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 221, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SisContque");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 210, 70));

        btnEntrar.setBackground(java.awt.Color.lightGray);
        btnEntrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 150, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuário");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/s-new-01_0.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 280));
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 220, -1));

        lblSair.setBackground(new java.awt.Color(255, 255, 255));
        lblSair.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSair.setForeground(new java.awt.Color(255, 255, 255));
        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone_fechar.png"))); // NOI18N
        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });
        jPanel1.add(lblSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 20, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Faculdade de Tecnologia de Ourinhos - 2016");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo-azul-abstrato-hd (1).jpg"))); // NOI18N
        jLabel1.setText("Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
     
        String nome = txtUsuario.getText();
        String senha = txtSenha.getText();
        Thread thread1;
        Thread thread2;
        
        thread1 =  new Thread(){
            public void run(){
                for(int i = 0; i < 101;i++){
                    try {
                        sleep(40);
                        lblCarregando.repaint();
                        lblCarregando.setVisible(true);
                        jProgressBar1.setVisible(true);
                        jProgressBar1.setValue(i);
                        
                        if(jProgressBar1.getValue() <= 25){
                            lblCarregando.setText("Carregando Sistema...");
                            
                        }else if(jProgressBar1.getValue() <= 50){
                            lblCarregando.setText("Carregando o Bando de Dados...");
                            
                        }else if(jProgressBar1.getValue() <= 75){
                            lblCarregando.setText("Abrindo Tabelas");
                        }else if(jProgressBar1.getValue() == 100){
                            lblCarregando.setText("Abrindo Tela Inicial");
                        }
                    } catch (InterruptedException ex) {
                        
                    }
                }
            }
        };
         
         thread1.start();
         
         thread2 = new Thread(){
            public void run(){
                for(int i = 0; i < 101;i++){
                    try {
                        sleep(10);
                        
                         UsuarioDAO usuarioDAO = new UsuarioDAO();
                            Usuario usuario = usuarioDAO.ConfirmarUsuario(nome, senha);
                            if (txtUsuario.getText().equals("") || txtSenha.getText().equals("") || usuario == null) {

            txLoginErro.setText("Login ou Senha inválidos");
            jProgressBar1.setVisible(false);
            lblCarregando.setVisible(false);
          

        } else if (usuario != null) {

            String loginn = null;
            String senhaa = null;
            String nomee = null;// TODO add your handling code here:

            Connection con = null;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/sisloja", "root", "root");
                Statement stm = con.createStatement();
                String SQL = "Select * from usuario where login = '" + txtUsuario.getText() + "';";
                ResultSet rs = stm.executeQuery(SQL);

                while (rs.next()) {
                    loginn = rs.getString("login");
                    senhaa = rs.getString("senha");
                    nomee = rs.getString("nome");
                }
                if (txtUsuario.getText().equals(loginn) && txtSenha.getText().equals(senhaa)) {
                    
                    while(thread1.isAlive()){
                        
                    }
                    Boolean Status = true;
                    
                    TelaInicial telaIni = new TelaInicial(usuario);
                    telaIni.setVisible(true);
                    dispose();
                    TipoMovimentoDAO tipoMovimentoDAO = new TipoMovimentoDAO();
                    TipoMovimento tipoMov = tipoMovimentoDAO.buscar(4);

                    Movimento movimento = new Movimento();
                    movimento.setDataExecucao(new Date());
                    movimento.setTipoMovimento(tipoMov);
                    movimento.setUsuario(tipoUser);

                    MovimentoDAO movimentoDAO = new MovimentoDAO();
                    movimentoDAO.inserir(movimento);
                    
                    this.stop();
                }

            } catch (SQLException e) {
                e.printStackTrace(); //vejamos que erro foi gerado e quem o gerou  
                JOptionPane.showMessageDialog(null, "Erro na conexão, com o banco de dados!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } finally {
                try {
                    con.close();
                } catch (SQLException onConClose) {
                    //System.out.println("Houve erro no fechamento da conexão");  
                    JOptionPane.showMessageDialog(null, "Erro na conexão, com o banco de dados!", "Alerta!", JOptionPane.WARNING_MESSAGE);
                    onConClose.printStackTrace();
                }
            } // fim do bloco try-catch-finally
        }//else do login e senha vazios
           
                      
                    } catch (InterruptedException ex) {
                        
                    }
                }
            }
        };
         
         thread2.start();
         
         
         

      
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        // setForeground(Color.white);
    }//GEN-LAST:event_lblSairMouseExited

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        btnEntrar.setBackground(Color.darkGray);
        btnEntrar.setForeground(Color.white);
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        btnEntrar.setBackground(Color.lightGray);
        btnEntrar.setForeground(Color.black);
    }//GEN-LAST:event_btnEntrarMouseExited
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("basic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        
        ArrayList<Usuario> usuarios = (ArrayList<Usuario>) usuarioDAO.listar();
        
        if(usuarios.size() <= 0){
            PrimeiroInsert primeiroInsert = new PrimeiroInsert();
            primeiroInsert.inserirAdmin();
            
            JOptionPane.showMessageDialog( null, "Usuário padrão do sistema criado, \n Crie um novo usuário ou altere os dados padrão do usuário");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblCarregando;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel txLoginErro;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
