/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.CampoLimiter;
import dao.GeneroDAO;
import dominio.Genero;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruno
 */
public class TelaCalendario extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadGenero
     */
    public TelaCalendario() {
        initComponents();
        
        Calendar C = Calendar.getInstance();
        int mes = C.get(Calendar.MONTH);
        int nomes = mes + 2;
        if(nomes == 2){
        lblMes.setText("Janeiro" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 3){
        lblMes.setText("Fevereiro" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 4){
        lblMes.setText("Março" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 5){
        lblMes.setText("Abril" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 6){
        lblMes.setText("Maio" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 7){
        lblMes.setText("Junho" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 8){
        lblMes.setText("Julho" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 9){
        lblMes.setText("Agosto" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 10){
        lblMes.setText("Setembro" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 11){
        lblMes.setText("Outubro" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 12){
        lblMes.setText("Novembro" + " - " + (C.get(Calendar.YEAR)));
        }        
        if(nomes == 13){
        lblMes.setText("Dezembro" + " - " + (C.get(Calendar.YEAR)));
        }
        
        
        //limitar campos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMes = new javax.swing.JLabel();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(804, 461));
        setMinimumSize(new java.awt.Dimension(804, 461));
        setName("GeneroPainel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1190, 630));

        lblMes.setBackground(new java.awt.Color(0, 0, 0));
        lblMes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblMes.setForeground(new java.awt.Color(255, 255, 255));

        jDayChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDayChooser1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDayChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(535, Short.MAX_VALUE)
                .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDayChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel lblMes;
    // End of variables declaration//GEN-END:variables
}