/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Willian
 */
public class TelaBackup extends javax.swing.JFrame {

    /**
     * Creates new form TelaBckp
     */
    public TelaBackup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRecuperarBackup = new javax.swing.JButton();
        btnRealizarBackup = new javax.swing.JButton();
        btnRecuperarBackup1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Backup");

        btnRecuperarBackup.setBackground(java.awt.Color.darkGray);
        btnRecuperarBackup.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRecuperarBackup.setForeground(new java.awt.Color(255, 255, 255));
        btnRecuperarBackup.setText("Recuperar Backup");
        btnRecuperarBackup.setBorderPainted(false);
        btnRecuperarBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecuperarBackup.setFocusPainted(false);
        btnRecuperarBackup.setFocusable(false);
        btnRecuperarBackup.setPreferredSize(new java.awt.Dimension(83, 31));
        btnRecuperarBackup.setRequestFocusEnabled(false);
        btnRecuperarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarBackupActionPerformed(evt);
            }
        });

        btnRealizarBackup.setBackground(java.awt.Color.darkGray);
        btnRealizarBackup.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRealizarBackup.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarBackup.setText("Realizar Backup");
        btnRealizarBackup.setBorderPainted(false);
        btnRealizarBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizarBackup.setFocusPainted(false);
        btnRealizarBackup.setFocusable(false);
        btnRealizarBackup.setPreferredSize(new java.awt.Dimension(83, 31));
        btnRealizarBackup.setRequestFocusEnabled(false);
        btnRealizarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarBackupActionPerformed(evt);
            }
        });

        btnRecuperarBackup1.setBackground(java.awt.Color.darkGray);
        btnRecuperarBackup1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRecuperarBackup1.setForeground(new java.awt.Color(255, 255, 255));
        btnRecuperarBackup1.setText("Concluir");
        btnRecuperarBackup1.setBorderPainted(false);
        btnRecuperarBackup1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecuperarBackup1.setFocusPainted(false);
        btnRecuperarBackup1.setFocusable(false);
        btnRecuperarBackup1.setPreferredSize(new java.awt.Dimension(83, 31));
        btnRecuperarBackup1.setRequestFocusEnabled(false);
        btnRecuperarBackup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarBackup1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecuperarBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnRecuperarBackup1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(142, 142, 142))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnRealizarBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRecuperarBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnRecuperarBackup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecuperarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarBackupActionPerformed
    
        try {
            Runtime.getRuntime().exec("cmd.exe /c C:\\xampp\\mysql\\bin\\mysqldump -u root < C:\\Users\\Bruno\\Desktop\\Backup\\SisContqueBackup.sql");
            JOptionPane.showMessageDialog(null, "Backup recuperado com sucesso");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "erro" + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnRecuperarBackupActionPerformed

    private void btnRealizarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarBackupActionPerformed
        try {
            File file = new File("C:\\Users\\Bruno\\Desktop\\Backup");
            file.mkdir();
            String dump = "cmd.exe /c C:\\xampp\\mysql\\bin\\mysqldump.exe -u root -h localhost sisloja > C:\\Users\\Bruno\\Desktop\\Backup\\SisConqueBackup.sql";
            Runtime bkp = Runtime.getRuntime();
            bkp.exec(dump);
            JOptionPane.showMessageDialog(null, "Backup realizado com sucesso!");
            Runtime.getRuntime().exec("explorer C:\\Users\\Bruno\\Desktop\\Backup");
            } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "erro" + ex.getMessage());
        }
        TelaInicial ti = null;
        ti.setExtendedState(ICONIFIED);
        
    }//GEN-LAST:event_btnRealizarBackupActionPerformed

    private void btnRecuperarBackup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarBackup1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRecuperarBackup1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarBackup;
    private javax.swing.JButton btnRecuperarBackup;
    private javax.swing.JButton btnRecuperarBackup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
